name: Build Linux

on:
  push:
  pull_request:

jobs:
    linux:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          target: [x86_64, i686]
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: 3.9
            architecture: x64
        - name: Build wheels
          uses: PyO3/maturin-action@v1
          with:
            target: ${{ matrix.target }}
            manylinux: auto
            args: --release --out dist
            before-script-linux: |
              yum install -y alsa-lib-devel pkgconfig
        - name: Install built wheel
          if: matrix.target == 'x86_64'
          run: |
            pip install rpaudio --no-index --find-links dist --force-reinstall
            python -c "import rpaudio"
        - name: Upload wheels
          uses: actions/upload-artifact@v3
          with:
            name: wheels
            path: dist