# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing
from enum import Enum, auto

class ChangeSpeed:
    duration: typing.Optional[float]
    start_val: typing.Optional[float]
    end_val: typing.Optional[float]
    apply_after: typing.Optional[float]
    def __new__(cls,duration = ...,start_val = ...,end_val = ...,apply_after = ...): ...

class FadeIn:
    duration: typing.Optional[float]
    start_val: typing.Optional[float]
    end_val: typing.Optional[float]
    apply_after: typing.Optional[float]
    def __new__(cls,duration = ...,start_val = ...,end_val = ...,apply_after = ...): ...

class FadeOut:
    duration: typing.Optional[float]
    start_val: typing.Optional[float]
    end_val: typing.Optional[float]
    apply_after: typing.Optional[float]
    def __new__(cls,duration = ...,start_val = ...,end_val = ...,apply_after = ...): ...

class ActionType(Enum):
    FadeIn = auto()
    FadeOut = auto()
    ChangeSpeed = auto()

