name: Rename Files

on:
  push:
    branches:
      - experimental
      - main

jobs:
  Experimental:
    if: github.ref == 'refs/heads/experimental'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rename CONTRIBUTING.md to README.md
        run: |
          if [ -f CONTRIBUTING.md ]; then
            mv CONTRIBUTING.md README.md
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add README.md
            git commit -m 'Rename CONTRIBUTING.md to README.md'
            git push
          else
            echo 'CONTRIBUTING.md not found, no changes made.'
          fi

  Main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rename README.md to CONTRIBUTING.md
        run: |
          if [ -f README.md ]; then
            mv README.md CONTRIBUTING.md
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add CONTRIBUTING.md
            git commit -m 'Rename README.md to CONTRIBUTING.md'
            git push
          else
            echo 'README.md not found, no changes made.'
          fi
      - name: Delete requirements.txt
        run: |
          if [ -f requirements.txt ]; then
            rm requirements.txt
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add -u requirements.txt
            git commit -m 'Delete requirements.txt'
            git push
          else
            echo 'requirements.txt not found, no changes made.'
          fi
