name: preflight-release

on:
  workflow_run:
    workflows:
      # - Build macOS
      # - Build Windows
      # - Build Linux
      # - Build Linux-Cross
      # - Build Musllinux
      # - Build Musllinux-Cross
      - Tst
    types:
      - completed

jobs:
  preflight-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine TWINE_PASSWORD
        run: |
          chmod +x .github/workflows/scripts/set-twine-secret.sh
          .github/workflows/scripts/set-twine-secret.sh