name: Release

on:
  push:
    branches:
      - experimental
      - main
    tags:
      - 'v*.*.*'
  workflow_run:
    workflows: ["Build macOS", "Build Windows", "Build Linux", "Build Linux-Cross", "Build Musllinux", "Build Musllinux-Cross"]
    types:
      - completed

jobs:
  independent-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare release
        run: |
          chmod +x .github/workflows/scripts/set-twine-secret.sh
          .github/workflows/scripts/set-twine-secret.sh
          echo "Current branch or tag: ${GITHUB_REF#refs/heads/}"

  release:
    runs-on: ubuntu-latest
    needs: ["independent-release"]
    steps:
      - uses: actions/checkout@v4

      - name: Determine TWINE_PASSWORD
        run: scripts/set-twine-secret.sh

      - name: Download all wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ env.TWINE_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing dist/*
