name: Release

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed

jobs:
  Prepare:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' }} # Ensures this job runs only if triggered by `workflow_run`
    steps:
      - uses: actions/checkout@v4
      - name: Prepare release
        run: |
          echo "Current branch or tag: ${GITHUB_REF#refs/heads/}"
  
  release:
    runs-on: ubuntu-latest
    needs: ["Prepare"]
    
    steps:
      
      
      - name: Download all wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ env.TWINE_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing dist/*
