name: Release

on:
  push:
    branches:
      - docs
    tags:
      - 'v*.*.*'
  workflow_run:
    workflows: ["Build macOS", "Build Windows", "Build Linux", "Build Linux-Cross", "Build Musllinux", "Build Musllinux-Cross"]
    types:
      - completed

jobs:
  independent-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare release
        run: echo "Preparing for release to TEST PyPI..."

  release:
    runs-on: ubuntu-latest
    needs: ["independent-release"]
    steps:
      - name: Download wheels from macOS
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Download wheels from Windows
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Download wheels from Linux
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Download wheels from Linux-Cross
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Download wheels from Musllinux
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - name: Download wheels from Musllinux-Cross
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: dist

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing dist/*
