name: Download Built Artifact
run-name: ${{ github.actor }} is testing out Download Artifact 🚀

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Install GitHub CLI
      run: |
        curl -sL https://github.com/cli/cli/releases/download/v2.27.0/gh_2.27.0_linux_amd64.deb -o gh.deb
        sudo dpkg -i gh.deb
        gh --version
    
    - name: Authenticate GitHub CLI
      run: gh auth login --with-token
      env:
        GITHUB_TOKEN: ${{ secrets.ARTIFACT_DEPLOY_TOKEN }}

    - name: Download artifact
      run: |
        OTHER_REPO="USER/REPO"
        WF_NAME="action-file.yml"
        ARTIFACT_NAME="test_artifact"
        RUN_ID=$(gh run list --repo ${OTHER_REPO} --workflow ${WF_NAME} --json databaseId --jq '.[0].databaseId')
        gh run download --repo ${OTHER_REPO} --run-id ${RUN_ID} --name ${ARTIFACT_NAME} --dir ./artifacts
        # List the artifact directory/files
        ls -lR ./artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.ARTIFACT_DEPLOY_TOKEN }}